<?php
// Internacionalizacao cn
return array(
'dict_projectname' => 'Archives World Map',
'dict_theopenandcollaborative' => 'The open and collaborative',
'dict_Languages' => '中文',
'dict_archivesname' => '机构 (面向公众开放的档案馆)',
'dict_archivesaddress' => '地址',
'dict_archivescity' => '城市',
'dict_archivesdistrict' => '区县',
'dict_archivescountry' => '国家',
'dict_archivesurl' => '链接',
'dict_archivesemail' => '邮箱',
'dict_archiveslatitude' => '纬度',
'dict_archiveslongitude' => '经度',
'dict_archivesyourname' => 'Your name (optional)',
'dict_archivesyouremail' => 'Your email (optional)',
'dict_archivesstatus' => 'Status',
'dict_sendtoinclusion' => '发送给档案馆世界地图',
'dict_map' => 'map',
'dict_collaborator' => '合作者姓名',
'dict_collaboratoryou' => '写下您的姓名，以方便我们感谢',
'dict_collaboratoremail' => '合作者邮箱',
'dict_collaboratoremailobs' => '我们将不会把它显示给公众',
'dict_addarchives' => '增加一个机构',
'dict_about' => '关于',
'dict_home' => '主页',
'dict_contact' => 'Contact',
'dict_createdby' => 'Created by',
'dict_textabout' => '<p>这是档案馆世界地图，一个映射我们星球上每一个档案机构的合作项目。也许这个目标听起来很远大，但随着很多人的努力我们可以走得更远。</p><p>任何人都可以通过点击 <a href="http://map.arquivista.net/add">添加一个机构</a> 来向我们发送关于档案馆的信息。 当你向地图上添加机构时，<a href="http://ricardo.arquivista.net/english">项目维护人员</a> 项目维护人员会对数据进行检查,然后将尽可能快地开放这些数据。数据库的使用是免费的，而且有望让其它项目也可使用这些数据。<p>档案馆世界地图网站和数据库达到一个足够稳定的状态以接收和存储可供多年使用的数据。</p><p>The Archives World Map costs around 150 € a month to exist and will be funded by the maintainer. If you want to collaborate financially for the computing resources and working hours costs for the software improvement, you can use the button at the end of this page to sign a monthly donation to the project.</p><p>You can help translating the website and software for your language also. Is just a file with around 50 phrases or words to be translated. To help in this way just send an email to <img src="https://map.arquivista.net/etc/ricardoemail.png">.</p><p>To receive emails about news and improvements of this project sign the email group (just the maintainer can send emails) at <a href="https://groups.google.com/d/forum/archives-world-map" target="_blank">https://groups.google.com/d/forum/archives-world-map</a>.</p>',
'dict_howfindcoordinates' => 'How to <a href="https://itouchmap.com/latlong.html" target="_blank">discover it</a>?',
'dict_textcontactpage' => 'We will have a contact form soon. Today you can send a message to <img src="https://map.arquivista.net/etc/ricardoemail.png">.',
'dict_thankscolab' => 'Thank you for your collaboration! The records will be verified soon to be published in the map.',
'dict_adddone' => 'Your submission was sent for verification. If everything be ok, the suggestion will appear soon in the Archives World Map! Thank you!<br> - <i>Ricardo Sodré Andrade, Archives World Map Maintainer</i>',
'dict_addfail' => 'Your submission was not sent. Maybe you did not checked the verification box (captcha) in add form. Please, try again or contact the project maintainer.',
'dict_monthly' => 'monthly',
'dict_textthankyoupage' => 'Thank you for your monthly contribution! With your help we will keep the Archives World Map alive!',
'dict_nameauthorisedform' => '如果可以的话，请使用 <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_EN.pdf" target="_blank">《档案馆藏机构著录规则》第16页</a> 解释的名称授权表。',
'dict_identifier' => 'Identifier',
'dict_identifierform' => '如果可以的话，请输入 <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_EN.pdf" target="_blank">《档案馆藏机构著录规则》第16页</a> 说明的标识符。',
'dict_location' => 'Location',
'dict_moreinformation' => 'More information',
'dict_institution' => '机构',
'dict_search' => '搜索',
'dict_searchresults' => 'Search result for',
'dict_searchourdatabase' => 'Search our database',
'dict_awmwascreatedby' => 'Archives World Map (<a href="https://github.com/rsandrade/archives-worldmap" target="_blank">GitHub</a>) was created by<br><a href="http://ricardo.arquivista.net/english" target="_blank">Ricardo Sodré Andrade</a>',
'dict_infoarchives' => 'Information about the Institution', 
'dict_stats' => '数据',
'dict_statsof' => '档案馆世界地图的统计数据',
'dict_institutionsdb' => 'Institutions',
'dict_top10countries' => 'Top 10 (countries)',
'dict_decimaldegreesplease' => 'If possible, in <a href="https://en.wikipedia.org/wiki/Decimal_degrees" target="_blank">Decimal Degrees</a>',
'dict_facebookcommunity' => 'Facebook community',
);
