"""ISO 3166-1 alpha-2 country code to name and flag emoji mapping."""

COUNTRIES = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AO": "Angola",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BA": "Bosnia and Herzegovina",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "BJ": "Benin",
    "BR": "Brazil",
    "BW": "Botswana",
    "CA": "Canada",
    "CH": "Switzerland",
    "CI": "Ivory Coast",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CU": "Cuba",
    "CV": "Cape Verde",
    "DE": "Germany",
    "DK": "Denmark",
    "DZ": "Algeria",
    "EE": "Estonia",
    "EG": "Egypt",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "GH": "Ghana",
    "GT": "Guatemala",
    "HK": "Hong Kong",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JP": "Japan",
    "KE": "Kenya",
    "KR": "South Korea",
    "LR": "Liberia",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MD": "Moldova",
    "MG": "Madagascar",
    "ML": "Mali",
    "MN": "Mongolia",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NG": "Nigeria",
    "NL": "Netherlands",
    "NO": "Norway",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PT": "Portugal",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SM": "San Marino",
    "SN": "Senegal",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "TD": "Chad",
    "TG": "Togo",
    "TN": "Tunisia",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}


def country_flag(code):
    """Convert a 2-letter country code to its flag emoji."""
    if not code or len(code) != 2:
        return ""
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in code.upper())


def country_display(code):
    """Return 'Flag Name (XX)' for a country code."""
    name = COUNTRIES.get(code, code)
    flag = country_flag(code)
    return f"{flag} {name}"
